-- Seed data for Feedback Intelligence Database
-- 74 realistic feedback items about Cloudflare Workers
-- Dates: Dec 20, 2025 - Jan 19, 2026 (30 days)
-- Dec 20-31: More critical issues & negative feedback
-- Jan 1-10: Mixed sentiment
-- Jan 11-19: More positive feedback & fewer critical issues

INSERT INTO feedback (source, content, user_type, sentiment, category, priority, created_at) VALUES
-- Dec 20-31: Critical period with many issues
('github', 'Workers deployment takes 30+ seconds in our CI/CD pipeline. This is too slow for rapid iteration.', 'enterprise', 'negative', 'performance', 'critical', '2025-12-20 10:23:00'),
('support', 'Getting intermittent 500 errors when Workers hit CPU time limit at exactly 50ms. Need better error messages.', 'pro', 'negative', 'bug', 'critical', '2025-12-20 09:15:00'),
('github', 'Workers cold starts are killing our application performance. 200-300ms delays on first request after idle.', 'enterprise', 'negative', 'performance', 'critical', '2025-12-21 08:30:00'),
('github', 'Workers KV eventual consistency bit us in production. Cache invalidation led to stale data for 60+ seconds.', 'enterprise', 'negative', 'bug', 'critical', '2025-12-21 13:45:00'),
('support', 'Workers experiencing random 500ms+ latency spikes during peak hours. Affecting our SLA.', 'enterprise', 'negative', 'performance', 'critical', '2025-12-22 07:30:00'),
('email', 'Workers cron triggers missing last scheduled run. No way to debug why it didn''t execute.', 'enterprise', 'negative', 'bug', 'critical', '2025-12-22 10:20:00'),
('github', 'Workers CPU time limit of 50ms is too restrictive for image processing. Getting timeouts on every request.', 'pro', 'negative', 'performance', 'high', '2025-12-23 15:30:00'),
('github', 'Workers pricing is confusing. Hard to estimate costs before deploying with varying request volumes.', 'enterprise', 'negative', 'docs', 'high', '2025-12-23 14:15:00'),
('support', 'Workers build failing with "Module not found" but builds fine locally. Need better error messages.', 'pro', 'negative', 'bug', 'high', '2025-12-24 08:00:00'),
('github', 'Wrangler dev mode is laggy - 2-3 second delay between code change and reload. Frustrating for development.', 'free', 'negative', 'ux', 'high', '2025-12-24 14:10:00'),
('support', 'Would love to see Workers support for WebSockets with longer connection times. 15 minutes is too short.', 'enterprise', 'neutral', 'feature-request', 'high', '2025-12-25 10:45:00'),
('email', 'Need better documentation on Workers environment variables and secrets. The difference between them is unclear.', 'free', 'neutral', 'docs', 'medium', '2025-12-25 11:20:00'),
('discord', 'Can we get support for multiple environments (dev/staging/prod) in wrangler.toml? Currently duplicating config.', 'enterprise', 'neutral', 'feature-request', 'medium', '2025-12-26 16:30:00'),
('support', 'Workers needs better integration with observability tools - native OpenTelemetry support would be amazing.', 'enterprise', 'neutral', 'feature-request', 'medium', '2025-12-26 09:45:00'),
('support', 'Need a way to bulk update Workers routes. Currently have to configure one by one in the dashboard.', 'enterprise', 'neutral', 'feature-request', 'medium', '2025-12-27 14:20:00'),
('discord', 'Wrangler CLI is overwhelming for beginners. Too many commands, not enough guidance on which to use.', 'free', 'negative', 'ux', 'medium', '2025-12-27 16:00:00'),
('support', 'Workers Analytics Engine shows different request counts than the dashboard. Which one is correct?', 'pro', 'neutral', 'bug', 'medium', '2025-12-28 12:30:00'),
('discord', 'Service bindings make microservices architecture so easy! No HTTP overhead, just function calls.', 'pro', 'positive', 'ux', 'low', '2025-12-28 15:22:00'),
('email', 'Workers + KV binding is the perfect combo. Built a global edge cache without managing servers!', 'pro', 'positive', 'ux', 'low', '2025-12-29 09:15:00'),
('discord', 'Workers request handling is blazing fast! Our API response times dropped from 200ms to 20ms at the edge.', 'pro', 'positive', 'performance', 'low', '2025-12-29 11:30:00'),
('twitter', 'Migrated from Lambda to Workers and our cold start issues disappeared completely. Game changer!', 'enterprise', 'positive', 'ux', 'low', '2025-12-30 10:00:00'),
('twitter', 'Workers reduced our infrastructure costs by 80%. No servers to manage, just code!', 'pro', 'positive', 'performance', 'low', '2025-12-30 13:45:00'),
('discord', 'Durable Objects binding from Workers made building real-time features trivial. WebSocket support is perfect!', 'pro', 'positive', 'ux', 'low', '2025-12-31 11:00:00'),
('twitter', 'Workers bundling is lightning fast! TypeScript to deployed Worker in under 2 seconds.', 'free', 'positive', 'performance', 'low', '2025-12-31 12:00:00'),

-- Jan 1-10: Mixed sentiment period
('github', 'Workers Logpush is dropping logs during high traffic. Critical for compliance requirements.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-01 10:15:00'),
('support', 'Workers D1 database experiencing connection timeouts. Queries taking 3-5 seconds when they should be instant.', 'enterprise', 'negative', 'performance', 'high', '2026-01-02 08:30:00'),
('github', 'Workers R2 binding has inconsistent performance. Sometimes fast, sometimes 2+ second delays.', 'pro', 'negative', 'performance', 'high', '2026-01-02 14:20:00'),
('email', 'Wrangler tail command stops showing logs after a few minutes. Have to restart constantly.', 'pro', 'negative', 'bug', 'medium', '2026-01-03 09:00:00'),
('discord', 'Workers script size limit of 1MB is too small for modern apps with dependencies.', 'enterprise', 'negative', 'feature-request', 'medium', '2026-01-03 15:30:00'),
('support', 'Need better TypeScript types for Workers bindings. Lots of "any" types causing bugs.', 'free', 'neutral', 'docs', 'medium', '2026-01-04 11:00:00'),
('github', 'Workers subrequests have weird caching behavior. Not respecting Cache-Control headers properly.', 'pro', 'negative', 'bug', 'high', '2026-01-04 16:45:00'),
('twitter', 'Workers AI is incredible! Built sentiment analysis in 10 lines of code. No ML expertise needed!', 'pro', 'positive', 'ux', 'low', '2026-01-05 10:30:00'),
('discord', 'The new Workers for Platforms is perfect for our multi-tenant SaaS. Customer isolation just works!', 'enterprise', 'positive', 'ux', 'low', '2026-01-05 14:00:00'),
('email', 'Workers Queues makes async processing so easy. No need to manage separate message queue infrastructure!', 'pro', 'positive', 'ux', 'low', '2026-01-06 09:30:00'),
('twitter', 'Workers Pages integration is seamless. Frontend and backend in one repo, deployed together!', 'free', 'positive', 'ux', 'low', '2026-01-06 12:15:00'),
('github', 'Workers secrets management needs improvement. No way to rotate secrets without downtime.', 'enterprise', 'negative', 'feature-request', 'medium', '2026-01-07 10:00:00'),
('support', 'Workers dashboard is slow when viewing large numbers of scripts. Takes 10+ seconds to load.', 'pro', 'negative', 'ux', 'medium', '2026-01-07 15:20:00'),
('discord', 'Wrangler publish is super fast now! Deployment time went from 15s to 3s.', 'free', 'positive', 'performance', 'low', '2026-01-08 11:45:00'),
('email', 'Workers Browser Rendering API is amazing! Generate PDFs and screenshots at the edge.', 'pro', 'positive', 'ux', 'low', '2026-01-08 14:30:00'),
('twitter', 'Hyperdrive made our database queries 3x faster. Connection pooling at the edge is brilliant!', 'enterprise', 'positive', 'performance', 'low', '2026-01-09 10:15:00'),
('github', 'Workers needs better error tracking integration. Hard to debug production issues.', 'enterprise', 'neutral', 'feature-request', 'medium', '2026-01-09 16:00:00'),
('discord', 'Workers + Vectorize for semantic search is ridiculously fast! Sub-50ms queries.', 'pro', 'positive', 'performance', 'low', '2026-01-10 12:00:00'),

-- Jan 11-19: Mostly positive period with improvements
('twitter', 'Just deployed my first Worker! The DX is incredible - from code to production in seconds. Love it!', 'free', 'positive', 'ux', 'low', '2026-01-11 14:30:00'),
('discord', 'The Workers AI integration is a game changer. Built an AI chatbot in under an hour without managing any infrastructure.', 'pro', 'positive', 'ux', 'low', '2026-01-11 16:45:00'),
('email', 'Workers Smart Placement optimized our multi-region app automatically. Latency dropped 40%!', 'enterprise', 'positive', 'performance', 'low', '2026-01-12 09:00:00'),
('twitter', 'Workers for Platforms makes it trivial to let users deploy their own code to our infrastructure!', 'enterprise', 'positive', 'ux', 'low', '2026-01-12 13:30:00'),
('discord', 'Wrangler dev now supports breakpoints! Debugging Workers locally just got 10x easier.', 'pro', 'positive', 'ux', 'low', '2026-01-13 10:15:00'),
('github', 'Workers D1 is production-ready! Running our API on serverless SQLite with zero issues.', 'pro', 'positive', 'performance', 'low', '2026-01-13 15:00:00'),
('twitter', 'The new Workers Analytics is so detailed. Finally can see exactly what''s happening at the edge!', 'enterprise', 'positive', 'ux', 'low', '2026-01-14 11:30:00'),
('email', 'Workers cron triggers are rock solid. Running scheduled jobs for 6 months without a single miss!', 'pro', 'positive', 'ux', 'low', '2026-01-14 14:45:00'),
('discord', 'Service bindings between Workers make our microservices architecture lightning fast!', 'enterprise', 'positive', 'performance', 'low', '2026-01-15 09:30:00'),
('github', 'Workers + KV for session storage is perfect. Global replication with single-digit ms reads!', 'pro', 'positive', 'performance', 'low', '2026-01-15 12:00:00'),
('twitter', 'Wrangler tail with filtering is amazing for debugging production issues in real-time!', 'free', 'positive', 'ux', 'low', '2026-01-16 10:00:00'),
('email', 'Workers cache API is so flexible. Built custom caching logic in minutes!', 'pro', 'positive', 'ux', 'low', '2026-01-16 13:15:00'),
('discord', 'The Workers examples repository is incredibly helpful. Found solutions to every use case!', 'free', 'positive', 'docs', 'low', '2026-01-16 15:30:00'),
('support', 'Workers versioning UI could be improved. Hard to track which version is deployed where.', 'enterprise', 'neutral', 'feature-request', 'low', '2026-01-17 09:00:00'),
('github', 'Wrangler needs a way to preview changes before deploying. Would catch config errors early.', 'pro', 'neutral', 'feature-request', 'medium', '2026-01-17 11:30:00'),
('twitter', 'Workers reduced our API latency from 200ms to 15ms. Customers are loving the speed!', 'enterprise', 'positive', 'performance', 'low', '2026-01-17 14:00:00'),
('discord', 'Built a real-time collaborative editor with Durable Objects. The DX is unmatched!', 'pro', 'positive', 'ux', 'low', '2026-01-18 10:30:00'),
('email', 'Workers Streams API makes handling large files trivial. No memory issues!', 'pro', 'positive', 'ux', 'low', '2026-01-18 13:00:00'),
('twitter', 'Just hit 1 million requests on Workers. Zero downtime, zero issues. Incredible!', 'enterprise', 'positive', 'performance', 'low', '2026-01-18 15:45:00'),
('github', 'Workers TypeScript support is first-class. Full type safety from local dev to production!', 'pro', 'positive', 'ux', 'low', '2026-01-19 09:00:00'),
('discord', 'The Workers community is so helpful! Got answers to complex questions in minutes.', 'free', 'positive', 'docs', 'low', '2026-01-19 11:30:00'),
('twitter', 'Workers pricing model scales perfectly. Started free, now processing millions of requests affordably!', 'enterprise', 'positive', 'ux', 'low', '2026-01-19 14:00:00'),
('email', 'Deployed a Workers API in production. Best decision we made this year!', 'pro', 'positive', 'performance', 'low', '2026-01-19 16:00:00'),

-- Additional varied feedback throughout the period
('github', 'Workers local development with wrangler dev matches production perfectly. No surprises!', 'free', 'positive', 'ux', 'low', '2025-12-26 10:00:00'),
('support', 'Would love native Workers support for GraphQL subscriptions over WebSockets.', 'pro', 'neutral', 'feature-request', 'medium', '2026-01-05 16:30:00'),
('twitter', 'Workers edge caching reduced our CDN costs by 90%. Just serving directly from the edge!', 'enterprise', 'positive', 'performance', 'low', '2026-01-10 14:30:00'),
('discord', 'Workers handles traffic spikes effortlessly. Went from 100 to 10k RPS without issues!', 'enterprise', 'positive', 'performance', 'low', '2026-01-15 11:00:00'),
('github', 'The Workers runtime is so small and fast. Cold starts are essentially non-existent!', 'pro', 'positive', 'performance', 'low', '2026-01-17 16:00:00'),
('email', 'Workers compatibility dates make upgrades smooth. Can test new features without breaking prod!', 'enterprise', 'positive', 'ux', 'low', '2026-01-18 10:00:00'),

-- Jan 20 - Feb 3: Extended data with ongoing critical and high priority issues
('github', 'Workers deployment failing with "binding not found" error. Worked yesterday, broken today.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-20 08:30:00'),
('support', 'Workers AI hitting rate limits during normal usage. Getting 429 errors every few minutes.', 'pro', 'negative', 'performance', 'high', '2026-01-20 10:15:00'),
('github', 'Workers KV consistency issues causing cart data loss in production. Urgent fix needed.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-20 14:00:00'),
('email', 'Need workers to support longer CPU time limits for ML inference. 50ms too short.', 'enterprise', 'neutral', 'feature-request', 'high', '2026-01-21 09:00:00'),
('discord', 'Workers Durable Objects are amazing for real-time features! Built a chat app in hours.', 'pro', 'positive', 'ux', 'low', '2026-01-21 11:30:00'),
('twitter', 'Just migrated our entire backend to Workers. Performance is incredible!', 'enterprise', 'positive', 'performance', 'low', '2026-01-21 15:00:00'),
('github', 'Workers cron trigger missed 3 scheduled runs this morning. No errors in logs.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-22 07:45:00'),
('support', 'Workers D1 queries timing out after recent update. Need rollback option.', 'pro', 'negative', 'performance', 'high', '2026-01-22 09:30:00'),
('email', 'Workers analytics dashboard is super helpful for debugging production issues!', 'pro', 'positive', 'ux', 'low', '2026-01-22 13:00:00'),
('github', 'Workers R2 upload speed degraded significantly. 5x slower than last week.', 'enterprise', 'negative', 'performance', 'high', '2026-01-23 08:00:00'),
('discord', 'Love the new Workers trace API! Makes debugging so much easier.', 'free', 'positive', 'ux', 'low', '2026-01-23 10:30:00'),
('support', 'Workers secret rotation causing downtime. Need zero-downtime secret updates.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-23 14:20:00'),
('twitter', 'Workers handled our product launch traffic spike flawlessly. 100k RPS no problem!', 'enterprise', 'positive', 'performance', 'low', '2026-01-24 09:00:00'),
('github', 'Workers build size limit blocking our deployment. Need 2MB limit instead of 1MB.', 'enterprise', 'negative', 'feature-request', 'high', '2026-01-24 11:00:00'),
('email', 'Workers + Vectorize made our semantic search lightning fast. Game changer!', 'pro', 'positive', 'performance', 'low', '2026-01-24 14:30:00'),
('github', 'Workers WebSocket connections dropping randomly. Affecting real-time features.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-25 08:15:00'),
('support', 'Need better error messages for Workers deployment failures. Current ones are cryptic.', 'pro', 'neutral', 'ux', 'medium', '2026-01-25 10:00:00'),
('discord', 'Workers for Platforms is perfect for our SaaS. Customer isolation works great!', 'enterprise', 'positive', 'ux', 'low', '2026-01-25 13:45:00'),
('github', 'Workers memory usage spiking unexpectedly. Getting OOM errors in production.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-26 07:30:00'),
('twitter', 'Workers edge network is incredible. Sub-20ms response times globally!', 'pro', 'positive', 'performance', 'low', '2026-01-26 11:00:00'),
('support', 'Workers Queues experiencing high latency. Messages delayed by 30+ seconds.', 'enterprise', 'negative', 'performance', 'high', '2026-01-26 14:00:00'),
('email', 'Workers TypeScript integration is seamless. Type safety everywhere!', 'free', 'positive', 'ux', 'low', '2026-01-27 09:30:00'),
('github', 'Workers environment variables not updating after deployment. Cache issue?', 'pro', 'negative', 'bug', 'high', '2026-01-27 12:00:00'),
('discord', 'Built a full API with Workers in a weekend. Developer experience is amazing!', 'free', 'positive', 'ux', 'low', '2026-01-27 15:30:00'),
('github', 'Workers dashboard showing incorrect metrics. Request count off by 50%.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-28 08:00:00'),
('support', 'Workers AI model response quality degraded. Same prompts giving worse results.', 'pro', 'negative', 'performance', 'high', '2026-01-28 10:30:00'),
('twitter', 'Workers reduced our infrastructure costs by 70%. No servers to manage!', 'enterprise', 'positive', 'performance', 'low', '2026-01-28 13:00:00'),
('email', 'Need Workers support for streaming responses. Current buffering causes delays.', 'enterprise', 'neutral', 'feature-request', 'high', '2026-01-29 09:00:00'),
('github', 'Workers binding to D1 database failing intermittently. 500 errors in production.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-29 11:30:00'),
('discord', 'Workers documentation is excellent. Found solutions to every problem quickly!', 'free', 'positive', 'docs', 'low', '2026-01-29 14:00:00'),
('support', 'Workers cold start latency increased after recent platform update.', 'pro', 'negative', 'performance', 'high', '2026-01-30 08:30:00'),
('twitter', 'Deployed our first Durable Object. The coordination primitives are brilliant!', 'pro', 'positive', 'ux', 'low', '2026-01-30 11:00:00'),
('github', 'Workers request tracing broken. Unable to debug production issues.', 'enterprise', 'negative', 'bug', 'critical', '2026-01-30 13:45:00'),
('email', 'Workers Smart Placement optimized our app automatically. Latency dropped 40%!', 'enterprise', 'positive', 'performance', 'low', '2026-01-31 09:00:00'),
('github', 'Workers rate limiting not working as documented. Requests exceeding limits.', 'pro', 'negative', 'bug', 'high', '2026-01-31 11:30:00'),
('discord', 'Workers browser rendering API is perfect for generating PDFs at scale!', 'pro', 'positive', 'ux', 'low', '2026-01-31 14:00:00'),
('github', 'Workers service binding authentication failing. Internal API calls blocked.', 'enterprise', 'negative', 'bug', 'critical', '2026-02-01 08:00:00'),
('support', 'Workers Hyperdrive connection pool exhausted. Database queries failing.', 'enterprise', 'negative', 'performance', 'high', '2026-02-01 10:30:00'),
('twitter', 'Workers made our global API deployment trivial. One command, worldwide!', 'enterprise', 'positive', 'ux', 'low', '2026-02-01 13:00:00'),
('email', 'Need Workers support for gRPC. REST-only limiting our architecture options.', 'enterprise', 'neutral', 'feature-request', 'medium', '2026-02-02 09:00:00'),
('github', 'Workers analytics showing data gaps. Missing 4 hours of metrics yesterday.', 'pro', 'negative', 'bug', 'high', '2026-02-02 11:00:00'),
('discord', 'Workers + Pages integration is seamless. Full-stack deployment in seconds!', 'free', 'positive', 'ux', 'low', '2026-02-02 14:30:00'),
('github', 'Workers KV namespace deletion stuck. Unable to clean up old resources.', 'enterprise', 'negative', 'bug', 'critical', '2026-02-03 08:30:00'),
('support', 'Workers AI inference slow during peak hours. Need better capacity planning.', 'pro', 'negative', 'performance', 'high', '2026-02-03 11:00:00'),
('twitter', 'Just hit 10 million requests on Workers. Zero issues, incredible reliability!', 'enterprise', 'positive', 'performance', 'low', '2026-02-03 14:00:00');
